---
# Original ChatGPT output for "Write an Ansible playbook to create 3 AWS ec2 instances"
- name: Create EC2 instances
  hosts: localhost
  gather_facts: false
  vars:
    region: us-east-1
    instance_type: t2.micro
    image: ami-0dba2cb6798deb6d8
    key_name: mykey
    security_group: mysecuritygroup
    vpc_subnet_id: subnet-1245abcdef
    count: 3
  tasks:
  - name: Create EC2 instances
    ec2:
      key_name: "{{ key_name }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      region: "{{ region }}"
      count: "{{ count }}"
      wait: yes
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: yes
    register: ec2
  - name: Wait for instances to be in running state
    wait_for:
      state: running
      host: "{{ item.public_ip }}"
      port: 22
    with_items: "{{ ec2.instances }}"
  - name: Print instance information
    debug:
      var: item
    with_items: "{{ ec2.instances }}"
