---
- name: setup check for code server
  when:
    - not teardown
  block:
    - name: Check to see if SSL cert already applied
      become: false
      community.crypto.get_certificate:
        host: "{{ student }}.{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}/editor"
        port: 443
      delegate_to: localhost
      run_once: true
      register: check_cert
      ignore_errors: true
      failed_when: false
      when: workshop_type is defined

    - name: Ensure Automation controller is online and working
      uri:
        url: https://localhost/api/v2/ping/
        method: GET
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        validate_certs: false
        force_basic_auth: true
      register: check_controller

- name: setup vscode for web browser access
  include_tasks: "codeserver.yml"
  when:
    - not teardown|bool
    - check_cert.cert is not defined
