---
s3_state: "present"
teardown: false
aap_dir: "/home/{{ username }}/aap_install"
codeserver_url: https://github.com/coder/code-server/releases/download/v4.9.1/code-server-4.9.1-amd64.rpm
codeserver_rescue_url: https://github.com/coder/code-server/releases/download/v4.9.1/code-server-4.9.1-amd64.rpm
username: "ec2-user"
vscode_extensions:
  - https://github.com/ansible/workshops/raw/devel/files/bierner.markdown-preview-github-styles-0.1.6.vsix
  - https://github.com/ansible/workshops/raw/devel/files/hnw.vscode-auto-open-markdown-preview-0.0.4.vsix
  - https://github.com/ansible/workshops/raw/devel/files/redhat.ansible-0.4.5.vsix
