---
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s'
ansible_ssh_pipelining: true

reg_name: TcpReceivePacketSize
reg_path: HKLM:\SYSTEM\CurrentControlSet\Services\DNS\Parameters
reg_data: 0xFFFF
reg_remediated_data: 0xFF00
reg_type: dword

lab_vuln_inventory_name: Vulnerable hosts
