---
ansible_user: "{{ lab_win_username }}"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_port: 5986
ansible_shell_type: cmd
ansible_password: "{{ lab_win_password }}"
