# Common user tasks
- name: Configure user - {{ lab_admin_username }}
  ansible.builtin.user:
    name: "{{ lab_admin_username }}"
    shell: /bin/bash
    password: "{{ lab_admin_password | password_hash }}"
    groups: wheel
    append: true

- name: Setup sudo - {{ lab_admin_username }}
  ansible.builtin.copy:
    content: "%{{ lab_admin_username }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ lab_admin_username }}_sudoers"
    mode: 0644
    owner: root
    group: root

- name: Create receptor group
  ansible.builtin.group:
    name: receptor
    state: present

- name: Create awx user and add to receptor group
  ansible.builtin.user:
    name: awx
    groups: receptor
    append: true
    home: /var/lib/awx
    shell: /bin/bash

- name: Create restricted user - {{ lab_student_username }}
  ansible.builtin.user:
    name: "{{ lab_student_username }}"
    shell: /bin/bash
    password: "{{ lab_student_password | password_hash }}"

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
