---
- name: Configure Windows
  hosts: windows
  gather_facts: true

  vars:
    slug: vuln-demo

  vars_files:
    - "{{ slug }}_vars.yml"
    - "vault_{{ slug }}_vars.yml"

  tasks:
    - name: Add windows roles Win2019 - {{ inventory_hostname }}
      ansible.windows.win_feature:
        name:
          - DNS
        state: present
        include_management_tools: true
      register: __win_feature
      when: '"Microsoft Windows Server 2019 Datacenter" in hostvars[inventory_hostname].ansible_os_name'

    - name: Reboot for feature install - {{ inventory_hostname }}
      ansible.windows.win_reboot:
      when:
        - __win_feature.reboot_required is defined
        - __win_feature.reboot_required

    # KB4569509: Guidance for DNS Server Vulnerability CVE-2020-1350
    - name: Add vulnerable Win2019 reg key
      ansible.windows.win_regedit:
        state: present
        path: "{{ reg_path }}"
        name: "{{ reg_name }}"
        type: "{{ reg_type }}"
        data: "{{ reg_data }}"
      when: '"Microsoft Windows Server 2019 Datacenter" in hostvars[inventory_hostname].ansible_os_name'
