---
- name: Configure localhost and deploy cloud instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    slug: vuln-demo

  vars_files:
    - "{{ slug }}_vars.yml"
    - "vault_{{ slug }}_vars.yml"

  tasks:
    # use '--tags install-collections' if using ansible-playbook
    - name: Download and upgrade collections - {{ inventory_hostname }}
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      loop:
        - ansible.workshops
        - amazon.aws
        - community.aws
        - community.general
        - ansible.posix
        - community.crypto
        - containers.podman
        - redhat_cop.controller_configuration
        - awx.awx
      register: __collection_install
      tags:
        - never
        - install-collections

    - name: Create cloud instances - {{ slug }}
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/ec2_instances.yml"
      when: ec2_instances is defined
      tags:
        - create-instances

    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
      tags:
        - always
