---
- name: Remediate affected registries
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Remediate registry - CVE-2020-1350
      ansible.windows.win_regedit:
        path: "{{ reg_path }}"
        name: "{{ reg_name }}"
        data: "{{ reg_remediated_data }}"
      register: __reg_key
